name: Install dependencies
on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Pre installed node versions
        run: node -v
      - name: Install nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Current node versions
        run: node -v
      - name: Current npm versions
        run: npm -v
