name: Install dependencies
on: [push]
env:
  FABRIC_VERSION: 2.2.2
  CA_VERSION: 1.4.9
  NODE_VER: 12.x
  

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Pre installed node versions
        run: node -v
      - name: Install nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Current node versions
        run: node -v
      - name: Current npm versions
        run: npm -v
      - name: List Existing files and folder
        run: ls -a
      # - name: Install fabric binaries
      #   run: |
      #     curl -L --retry 5 --retry-delay 3 https://hyperledger.jfrog.io/hyperledger/fabric-binaries/hyperledger-fabric-linux-amd64-${FABRIC_VERSION}-stable.tar.gz | tar xz
      #     curl -L --retry 5 --retry-delay 3 https://hyperledger.jfrog.io/hyperledger/fabric-binaries/hyperledger-fabric-ca-linux-amd64-${FABRIC_VERSION}-stable.tar.gz | tar xz
      # - name : List Current files and folders
      #   run: |
      #     ls -a
      #     tree
      # - name : List binary files 
      #   run: ls -a bin
      - name: clone repo using checkout action
        uses: actions/checkout@v1
      - name: List files
        run: ls -a
      - name: Download binaries and docker images
        run: |
          curl -sSL https://bit.ly/2ysbOFE | bash -s -- ${FABRIC_VERSION} ${CA_VERSION}  -s
          tree
      - name: Create network using leveldb and Certificate Authority
        run: |
          cd network
          ./network.sh up -ca
      - name: Create Channel called mychannel
        run: |
          cd network
          ./network.sh createChannel
      - name: Install libaries  for Chaincode
        run: |
          cd asset-transfer-basic/chaincode-javascript/
          npm install
      - name: Deploy Chaincode
        run: |
          cd network
          ./network.sh deployCC -ccn basic -ccp ../asset-transfer-basic/chaincode-javascript/ -ccl javascript -cci InitLedger 
      - name: Run Chaincode Tests
        run: |
          cd asset-transfer-basic/chaincode-javascript/
          npm run test
      - name: Install libaries for Application 
        run: |
          cd asset-transfer-basic/application-javascript
          npm install
      - name: Run test
        run: |
          cd asset-transfer-basic/application-javascript
          npm run test


        

