name: Install dependencies
on: [push]
env:
  FABRIC_VERSION: 2.4
  NODE_VER: 12.x
  

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Pre installed node versions
        run: node -v
      - name: Install nodejs 12
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Current node versions
        run: node -v
      - name: Current npm versions
        run: npm -v
      - name: List Existing files and folder
        run: ls -a
      # - name: Install fabric binaries
      #   run: |
      #     curl -L --retry 5 --retry-delay 3 https://hyperledger.jfrog.io/hyperledger/fabric-binaries/hyperledger-fabric-linux-amd64-${FABRIC_VERSION}-stable.tar.gz | tar xz
      #     curl -L --retry 5 --retry-delay 3 https://hyperledger.jfrog.io/hyperledger/fabric-binaries/hyperledger-fabric-ca-linux-amd64-${FABRIC_VERSION}-stable.tar.gz | tar xz
      # - name : List Current files and folders
      #   run: |
      #     ls -a
      #     tree
      # - name : List binary files 
      #   run: ls -a bin
      - name: clone repo using checkout action
        uses: actions/checkout@v1
      - name: List files
        uses: ls -a
