name: Test
on: [push]
env:
  FABRIC_VERSION: 2.2.2
  CA_VERSION: 1.4.9
  NODE_VER: '12'
  

jobs:
  test:
    strategy:
      matrix:
        chaincode: [basic, events]
        include:
          - chaincode: basic
            folderName: asset-transfer-basic
            parseFlagForInitFunction: -cci
            initFunction: InitLedger
          - chaincode: events
            folderName: asset-transfer-events       
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs ${NODE_VER}
        uses: actions/setup-node@v1
        with:
          node-version: ${NODE_VER}
      - name: clone repo using checkout action
        uses: actions/checkout@v1
      - name: List files
        run: ls -a
      - name: Download binaries and docker images
        run: |
          curl -sSL https://bit.ly/2ysbOFE | bash -s -- ${FABRIC_VERSION} ${CA_VERSION}  -s
          tree
      - name: Create network using leveldb and Certificate Authority
        run: |
          cd network
          ./network.sh up -ca
      - name: Create Channel called mychannel
        run: |
          cd network
          ./network.sh createChannel
      - name: Install libaries  for Chaincode
        run: |
          cd ${{matrix.folderName}}/chaincode-javascript/
          npm install
      - name: Deploy Chaincode
        run: |
          cd network
          ./network.sh deployCC -ccn ${{matrix.chaincode}} -ccp ../${{matrix.folderName}}/chaincode-javascript/ -ccl javascript ${{matrix.parseFlagForInitFunction}} ${{matrix.initFunction}} 
      - name: Run Chaincode Tests
        run: |
          cd ${{matrix.folderName}}/chaincode-javascript/
          npm run test
      - name: upload test coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-${{matrix.chaincode}}
          path: ${{matrix.folderName}}/chaincode-javascript/coverage
        
          


        

